### ISSUE TITLE
refac: API path 변경

### ISSUE THREAD

**Issue by bluayer** [sopt-makers/sopt-playground-frontend#109]
## ✨ 설명하기 

API Path를 좀 더 적절한 이름으로 변경 제안

## ✅ To Do List 

- [x] /api/v1/register/sendEmail -> /api/v1/registration/email
- [x] /api/v1/register/checkToken -> /api/v1/registration/info
- [ ] /api/v1/presigned-url -> /api/v1/image/url

**Comment by NamJwong** [comment]
@bluayer  1, 2번 둘 다 좋은 것 같아요

3번은 정확히 어떤 response를 받는건지 모르겠는데 지금 테스트도 안돼서 다른 분들 의견 참고하시거나 response 알려주시면 좋을 것 같습니다 😀

**Comment by bluayer** [comment]
@NamJwong 3번은 이미지 업로드할 때 사용하는 API고, S3 presigned된 URL을 내려주는 역할!

1. 이미지 업로드 요청 -> 서버 api 호출
2. 서버에서 S3에 presigned url 요청하고 받아옴
3. 서버는 브라우저로 presigned url을 전달
4. 브라우저에서 AWS presigned url로 이미지 upload

이렇게 하는 이유는
1. 브라우저 - 서버 - aws로 업로드하면 서버 자원이 많이 점유당하고 심지어 느림
2. 브라우저에서만 처리할 수도 있는데, credential이 탈취당할 가능성이 높아져서 보안적으로 안 좋음

**Comment by juno7803** [comment]
@bluayer 저도 1,2 둘다 괜찮습니다~! 
3번은 response만 `presigned-url` 방식인 것 알 수 있게 프로퍼티 지금과 같이 유지해주시면 될 것 같습니당~

**Comment by NamJwong** [comment]
@bluayer 와아 자세한 설명 정말 감사합니다!! 저도 3번 presigned-url 방식인 것 알 수 있었음 해서 기존대로 유지하거나 `/api/v1/image/presigned-url` 이렇게는 어떨까 싶습니다!

**Comment by bluayer** [comment]
@juno7803 @NamJwong image는 의미 전달 관련해서 급하지 않은 거 같아서, 일단 위의 registration 부분만 처리했음!

**Comment by NamJwong** [comment]
완료
