### ISSUE TITLE
fix: 동적 라우팅 404 에러 fix

### ISSUE THREAD

**Issue by NamJwong** [sopt-makers/sopt-playground-frontend#158]
## ✨ 설명하기 
https://github.com/sopt-makers/sopt-internal-frontend/pull/143 에서 임시 방편으로 해결한 코드를 되돌리고 에러를 해결합니다

## ✅ To Do List 

- [ ] 작-업 1
- [ ] 작-업 2
- [ ] 작-업 3

**Comment by Tekiter** [comment]
우리 그다음에 원래대로 바꾸지 않고 이대로 유지하기로 했지?
