### ISSUE TITLE
fix: 윈도우에서 select option 글씨 안 보이는 버그

### ISSUE THREAD

**Issue by NamJwong** [sopt-makers/sopt-playground-frontend#208]
## ✨ 설명하기 
![image](https://user-images.githubusercontent.com/73823388/203241124-7fe71ee6-4a5c-47ed-b1ed-ff469f07c2a4.png)

## ✅ To Do List 

- [ ] 작-업 1
- [ ] 작-업 2
- [ ] 작-업 3

**Comment by Tekiter** [comment]
#841 에서 해결
