### ISSUE TITLE
fix: 프로필 업로드 > 유효성 검증 시 의존성이 있는 input의 변경 사항이 errors에 바로 반영되지 않는 버그 fix

### ISSUE THREAD

**Issue by NamJwong** [sopt-makers/sopt-playground-frontend#315]
## ✨ 설명하기 

https://user-images.githubusercontent.com/73823388/210096152-298717cc-5c93-4216-a121-9cda80fa4d93.mov

회사 input 변경 사항이 제대로 trigger 됐으면 에러 메시지가 사라져야 함
useEffect에 errors 의존성 걸어서 확인해본 결과 errors에 반영이 안됨

## ✅ To Do List 

- [ ] register deps 옵션 활용해보기
  - [ ] [이 글](https://velog.io/@centraldogma99/react-hook-form%EC%97%90%EC%84%9C-deps%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%A0%EB%95%8C%EB%8A%94-%EC%A1%B0%EC%8B%AC%ED%95%98%EC%84%B8%EC%9A%94) 참고하여 문제 없는지 확인

**Comment by Tekiter** [comment]
이거도 어제 수정한 유저 삭제 버그의 원인과 관련이 있지 않을까 생각..!
