### ISSUE TITLE
chore: 불필요한 디펜던시 제거 및 dev로 이동

### ISSUE THREAD

**Issue by juno7803** [sopt-makers/sopt-playground-frontend#327]
## ✨ 설명하기 
- "eslint-plugin-simple-import-sort"
- "storybook-addon-next-router"
- "@types/react-datepicker
- "react-spinners" (가능하다면 loading으로 대체)

## ✅ To Do List 

- [ ] 작-업 1
- [ ] 작-업 2
- [ ] 작-업 3

**Comment by NamJwong** [comment]
오오 선생님 혹시 저보다 빨리 작업하시게 된다면 여기 있는 것들도 함께 부탁드립니다 ,, https://github.com/sopt-makers/sopt-playground-frontend/issues/277

**Comment by juno7803** [comment]
@NamJwong 오 그냥 보다가 우연히 생각나서 올린건데 이미 이슈에 있었군요..!
좋습니닷~~
