### ISSUE TITLE
fix: 엉뚱한 쿼리 파라미터 받을 시 404 페이지 띄우기

### ISSUE THREAD

**Issue by NamJwong** [sopt-makers/sopt-playground-frontend#366]
## ✨ 설명하기 
ex) edit 쿼리에 true와 false 이외의 값

## ✅ To Do List 

- [ ] 작-업 1
- [ ] 작-업 2
- [ ] 작-업 3

**Comment by Tekiter** [comment]
Edit쿼리 삭제로 인한 Close
