### ISSUE TITLE
fix: 수정 페이지 쿼리 파라미터 edit=id 형태로 변경

### ISSUE THREAD

**Issue by NamJwong** [sopt-makers/sopt-playground-frontend#368]
## ✨ 설명하기 
edit=true&id=1를 edit=1로 변경

## ✅ To Do List 

- [ ] 작-업 1
- [ ] 작-업 2
- [ ] 작-업 3

**Comment by Tekiter** [comment]
새로운 아이디어: 페이지 안에서 파라미터로 구별하지 말고, 아예 페이지를 따로 파는건 어때? 컴포넌트만 공유하고!
잠재적인 버그를 미연에 방지할 수 있을것 같아.

**Comment by NamJwong** [comment]
@Tekiter 
난 매우 좋다고 생각해!
지금 한 페이지 컴포넌트에서 수정이랑 등록 로직이 섞여서 너무 어지러워ㅠㅠ

**Comment by NamJwong** [comment]
업로드 페이지랑 수정 페이지를 분리하기로
