### ISSUE TITLE
refactor: MemberSearch 쪽 headless-ui 걷어내기

### ISSUE THREAD

**Issue by juno7803** [sopt-makers/sopt-playground-frontend#403]
## ✨ 설명하기 
- 쉽지 않은 싸움이 될 것 같습니다. (headless-ui 쪽 tscheck를 꺼뒀었기 때문...)
- radix로 변경합니다.

## ✅ To Do List 

- [x] headless-ui => radix-ui (radix 기반으로 만들어진 cmdk)
- [ ] react-hook-form 타입 수정 (진행 중)
- [ ] 쿼리키 상수화 (객체화)

**Comment by Tekiter** [comment]
radix-ui 에는 headless-ui의 ComboBox와 대응되는 컴포넌트는 없지만, [CmdK](https://github.com/pacocoursey/cmdk)라는 라이브러리를 [함께 써서 구현](https://codesandbox.io/p/sandbox/radix-dropdown-combobox-1x6e3k?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A39%2C%22endLineNumber%22%3A68%2C%22startColumn%22%3A39%2C%22startLineNumber%22%3A68%7D%5D)할 수 있나봐요! 한번 참고해보세요!



https://github.com/radix-ui/primitives/issues/1342

**Comment by juno7803** [comment]
@Tekiter 참고할게요 ㅎㅎ 고마워!!
