### ISSUE TITLE
refactor: 프로젝트 업로드 폼 개선

### ISSUE THREAD

**Issue by Tekiter** [sopt-makers/sopt-playground-frontend#450]
## ✅ To Do List

- [x] 기본 구조 다시 잡기
- [ ] 폼 항목 모두 구현하기
- [ ] API 연동 추가하기
- [ ] 현재 진행상황 추가하기

## Form To do
- [x] 멤버
- [x] 기간
- [x] 이름

**Comment by juno7803** [comment]
@Tekiter refactor/#450-form 으로 작업하겠습니다 🙇🏻‍♂️
