### ISSUE TITLE
refactor: src 폴더 만들어서 root 폴더 정리하기

### ISSUE THREAD

**Issue by NamJwong** [sopt-makers/sopt-playground-frontend#497]
## ✨ 설명하기

현재 아래와 같이 root 폴더가 매우 복잡하기 때문에 @Tekiter 가 제안한 리팩토링

<img width="607" alt="image" src="https://user-images.githubusercontent.com/73823388/225229323-24fa98e3-0327-4ab4-9597-af6d4cc6dff1.png">

**Comment by NamJwong** [comment]
@Tekiter 옹옹 담에 시간 맞춰서 해보자~

**Comment by Tekiter** [comment]
#935 에서 해결
